### PR TITLE
Add an option to open app with JIT (rework)

### PR DESCRIPTION
**Pull request by khanhduytran0**
Rework of #702:
- Removed `task_for_pid-allow` entitlement
- Moved enable JIT function to root helper

### CODE REVIEW

**Comment by alfiecg24** [comment]
Could you add more descriptive error messages/codes? e.g. if an app doesn't have `get-task-allow`, tell the user it cannot be debugged/use JIT.

**Comment by khanhduytran0** [comment]
Certainly, but handling the lack of get-task-allow is currently done by hiding the button, but I’m concerned that it might be ineffective (requires loading entitlements when user taps an app) so please give me advice, whether it should check after user presses it or just check and hide it.

**Comment by alfiecg24** [comment]
Oh, I didn't see that. I think loading the entitlements of every app could cause performance issues, but I'm not 100% sure. Don't worry about the error messages though.

**Comment by khanhduytran0** [comment]
Entitlements are only loaded when you tap an app, I did a tiny bit of stress test using Settings’ entitlements on iPhone 6s+ and didn’t get any noticeable delay and memory usage. It should be good to go regardless. I’m unsure what to do with error reporting, it currently reports the exit code (usually errno), but it shouldn’t happen at all 🤔(I haven’t tried this on 17.0 though)

**Comment by AriyanYT** [comment]
Some apps Jit not showing like game app(Pubg)

**Comment by opa334** [comment]
Could we automate this?

App opens TrollStore URL scheme, TrollStore applies JIT flags and goes back to the app?

**Comment by khanhduytran0** [comment]
> Could we automate this?
> 
> App opens TrollStore URL scheme, TrollStore applies JIT flags and goes back to the app?

I’ve added this, please let me know what else I need to add.

**Review by churchdude144 — APPROVED** [review]

**Pull request merged**
